// swift-tools-version:5.9
//
// NockerlDesign: the Nockerl design framework as a SwiftPM package.
//
// Ships the generated design tokens (Sources/NockerlDesign/NockerlTokens.swift):
// NockerlDarkColors / NockerlLightColors (SwiftUI Color), NockerlRadius /
// NockerlElevation / NockerlSpace / NockerlFontSize (CGFloat), and the NockerlType
// ramp (Outfit), plus the SwiftUI component layer (Sources/NockerlDesign/Components:
// NockerlButton / NockerlIconButton / NockerlChip, shipped since v0.6.0). The token
// source is GENERATED by `bun run build` from tokens/*.json (the source of truth) and
// mirrored into Sources/ on every build; do not edit NockerlTokens.swift by hand.
// Components are authored code, verified on the macOS CI rail (swift.yml).
//
// Consume by pinning a git tag on the repo URL. See the Installation page and
// docs/decisions/0006 (versioning) + 0007 (architecture).
import PackageDescription

let package = Package(
    name: "NockerlDesign",
    platforms: [
        .macOS(.v12),
        .iOS(.v15),
        .tvOS(.v15),
        .watchOS(.v8),
    ],
    products: [
        .library(name: "NockerlDesign", targets: ["NockerlDesign"]),
    ],
    targets: [
        .target(
            name: "NockerlDesign",
            path: "Sources/NockerlDesign",
            // The bundled type faces: Outfit (the law-§11 ramp weights
            // 100/200/300/400/500) + Space Mono (the mono face), OFL-1.1. Copied
            // verbatim so CTFontManager can register them from `Bundle.module` at
            // load with ZERO app-side setup, resolving NockerlType's declared
            // families instead of silently falling back to SF.
            resources: [
                .copy("Resources/Fonts"),
            ]
        ),
        .testTarget(
            name: "NockerlDesignTests",
            dependencies: ["NockerlDesign"],
            path: "Tests/NockerlDesignTests"
        ),
    ]
)
