// swift-tools-version:5.9
//
// NockerlDesign: the Nockerl design framework as a SwiftPM package.
//
// Ships the generated design tokens (Sources/NockerlDesign/NockerlTokens.swift):
// NockerlDarkColors / NockerlLightColors (SwiftUI Color), NockerlRadius /
// NockerlElevation / NockerlSpace / NockerlFontSize (CGFloat), and the NockerlType
// ramp (Outfit), plus the SwiftUI component layer (Sources/NockerlDesign/Components:
// NockerlButton / NockerlIconButton / NockerlChip, shipped since v0.6.0). The token
// source is GENERATED by `bun run build` from tokens/*.json (the source of truth) and
// mirrored into Sources/ on every build; do not edit NockerlTokens.swift by hand.
// Components are authored code, verified on the macOS CI rail (swift.yml).
//
// Consume by pinning a git tag on the repo URL. See the Installation page for
// the version line and the package layout.
import PackageDescription

let package = Package(
    name: "NockerlDesign",
    platforms: [
        .macOS(.v12),
        .iOS(.v15),
        .tvOS(.v15),
        .watchOS(.v8),
    ],
    products: [
        .library(name: "NockerlDesign", targets: ["NockerlDesign"]),
    ],
    targets: [
        .target(
            name: "NockerlDesign",
            path: "Sources/NockerlDesign",
            // The bundled type faces: Outfit (the law-§11 ramp weights
            // 100/200/300/400/500) + Space Mono (the mono face), OFL-1.1. Copied
            // verbatim so CTFontManager can register them from `Bundle.module` at
            // load with ZERO app-side setup, resolving NockerlType's declared
            // families instead of silently falling back to SF.
            resources: [
                .copy("Resources/Fonts"),
                // The product marks, as a COMPILED asset catalog. `.process` rather than
                // `.copy` is load bearing: a catalog has to be run through actool to become
                // a usable Assets.car, and `.copy` would ship the raw directory, which
                // resolves to nothing at runtime while still building cleanly.
                //
                // A catalog is also the only workable shape here. SwiftUI cannot render a
                // raw SVG from a bundle, so the marks cannot simply be copied in as files;
                // catalogs do support SVG, and give light and dark switching plus vector
                // scaling at any size for free.
                //
                // GENERATED from logos/app-icons by `bun run build`, and `check:marks`
                // fails if the two drift. Do not edit the catalog by hand.
                .process("Resources/Marks.xcassets"),
            ]
        ),
        .testTarget(
            name: "NockerlDesignTests",
            dependencies: ["NockerlDesign"],
            path: "Tests/NockerlDesignTests"
        ),
    ]
)
