// Nockerl design tokens: GENERATED by Style Dictionary. Do not edit by hand.
// Source of truth: tokens/*.json  •  Build: bun run build

package com.dizyx.nockerl.design.tokens

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Dark-theme palette. Color(0xAARRGGBB). */
object NockerlDarkColors {
    val coreWhite = Color(0xFFFFFFFF)
    val coreBlack = Color(0xFF000000)
    val coreCyan300 = Color(0xFF5ED4E8)
    val coreCyan400 = Color(0xFF22D3EE)
    val coreCyan500 = Color(0xFF0CC0DF)
    val coreCyan600 = Color(0xFF0A9BB5)
    val coreCyan700 = Color(0xFF0891B2)
    val coreCyan800 = Color(0xFF0E7490)
    val coreCyan900 = Color(0xFF155E75)
    val coreOrange400 = Color(0xFFFB923C)
    val coreOrange500 = Color(0xFFF97316)
    val coreOrange600 = Color(0xFFEA580C)
    val coreStatusSuccess = Color(0xFF4CAF50)
    val coreStatusSuccessDeep = Color(0xFF2E7D32)
    val coreStatusWarning = Color(0xFFFFC107)
    val coreStatusWarningDeep = Color(0xFFB7791F)
    val coreStatusError = Color(0xFFEF5350)
    val coreStatusErrorDeep = Color(0xFFD32F2F)
    val coreCategoricalCyan400 = Color(0xFF22D3EE)
    val coreCategoricalOrange400 = Color(0xFFFB923C)
    val coreCategoricalIndigo400 = Color(0xFF818CF8)
    val coreCategoricalSky400 = Color(0xFF38BDF8)
    val coreCategoricalFuchsia400 = Color(0xFFE879F9)
    val coreCategoricalViolet400 = Color(0xFFA78BFA)
    val coreCategoricalPink400 = Color(0xFFF472B6)
    val coreCategoricalEmerald400 = Color(0xFF34D399)
    val coreCategoricalTeal400 = Color(0xFF2DD4BF)
    val coreCategoricalPurple400 = Color(0xFFC084FC)
    val coreCategoricalGreen400 = Color(0xFF4ADE80)
    val coreCategoricalSky600 = Color(0xFF0284C7)
    val coreCategoricalTeal600 = Color(0xFF0D9488)
    val coreCategoricalIndigo600 = Color(0xFF4F46E5)
    val coreLogoInk = Color(0xFF555555)
    val coreLogoInkHi = Color(0xFF222222)
    val coreLogoInkLo = Color(0xFF777777)
    val coreLogoInverse = Color(0xFFE5E5E5)
    val coreLogoInverseHi = Color(0xFFFFFFFF)
    val coreLogoInverseLo = Color(0xFFCCCCCC)
    val familyShellFs = Color(0xFF22D3EE)
    val familyAgent = Color(0xFFFB923C)
    val familyScheduling = Color(0xFF818CF8)
    val familyPlanning = Color(0xFF38BDF8)
    val familyExternal = Color(0xFFE879F9)
    val modelTypeGpu = Color(0xFFA78BFA)
    val modelTypeLlm = Color(0xFFC084FC)
    val modelTypeEmbedding = Color(0xFF34D399)
    val modelTypeVision = Color(0xFF38BDF8)
    val modelTypeAudio = Color(0xFFF472B6)
    val modelTypeCreative = Color(0xFFE879F9)
    val modelTypeUtility = Color(0xFF2DD4BF)
    val modelTypeTemperature = Color(0xFFFB923C)
    val fileTypeKotlin = Color(0xFFC084FC)
    val fileTypeTypescript = Color(0xFF38BDF8)
    val fileTypeJavascript = Color(0xFFFB923C)
    val fileTypeJson = Color(0xFF2DD4BF)
    val fileTypeCss = Color(0xFF818CF8)
    val fileTypeHtml = Color(0xFFE879F9)
    val fileTypeYaml = Color(0xFF34D399)
    val fileTypeShell = Color(0xFF4ADE80)
    val fileTypePython = Color(0xFF22D3EE)
    val fileTypeRust = Color(0xFFEF5350)
    val fileTypeImage = Color(0xFFA78BFA)
    val fileTypeFolder = Color(0xFF38BDF8)
    val fileTypeDefault = Color(0xFF6B6B6B)
    val taskStatusTodo = Color(0xFF6B6B6B)
    val taskStatusInProgress = Color(0xFF38BDF8)
    val taskStatusBlocked = Color(0xFFEF5350)
    val taskStatusDone = Color(0xFF4CAF50)
    val taskStatusCancelled = Color(0xFF6B6B6B)
    val taskPriorityLow = Color(0xFF2DD4BF)
    val taskPriorityMedium = Color(0xFFFFC107)
    val taskPriorityHigh = Color(0xFFFB923C)
    val taskPriorityUrgent = Color(0xFFEF5350)
    val notifSourceSystem = Color(0xFF818CF8)
    val notifSourceAgent = Color(0xFFFB923C)
    val notifSourceTask = Color(0xFF34D399)
    val notifSourceCi = Color(0xFFA78BFA)
    val notifSourceMention = Color(0xFFE879F9)
    val notifPriorityLow = Color(0xFF6B6B6B)
    val notifPriorityNormal = Color(0xFF38BDF8)
    val notifPriorityHigh = Color(0xFFEF5350)
    val modelBadgeLarge = Color(0xFFC084FC)
    val modelBadgeMedium = Color(0xFF818CF8)
    val modelBadgeSmall = Color(0xFF34D399)
    val modelBadgeLocal = Color(0xFF22D3EE)
    val modelBadgeOther = Color(0xFF6B6B6B)
    val canvas = Color(0xFF0A0B0D)
    val canvasAlt = Color(0xFF111317)
    val chatBg = Color(0xFF181B20)
    val canvasEdge = Color(0xFF2A2D33)
    val onCanvas = Color(0xFFE8E8E8)
    val onCanvasMuted = Color(0xFFA0A0A0)
    val cardSurface1 = Color(0xFF2C313A)
    val cardSurface2 = Color(0xFF333942)
    val cardSurface3 = Color(0xFF3A414A)
    val onCard = Color(0xFFE8E8E8)
    val onCardMuted = Color(0xFFA0A0A0)
    val cardHairline = Color(0x14FFFFFF)
    val chromeSurface = Color(0xFF15171A)
    val chromeActive = Color(0xFF1D2024)
    val onChrome = Color(0xFFE8E8E8)
    val onChromeMuted = Color(0xFFA0A0A0)
    val chromeHairline = Color(0x14FFFFFF)
    val surfaceTranslucencySidebar = Color(0x8C15171A)
    val sessionChipActive = Color(0xFF0CC0DF)
    val onSessionChip = Color(0xFF0A0B0D)
    val sessionChipInactive = Color(0xFF0A9BB5)
    val sessionChipNew = Color(0xFF4B5563)
    val cardAlt = Color(0xFF2C313A)
    val cardAlt2 = Color(0xFF363C45)
    val onCardAlt = Color(0xFFE8E8E8)
    val onCardAltMuted = Color(0xFFA0A0A0)
    val altHairline = Color(0x10FFFFFF)
    val userCard = Color(0xFF0C2A31)
    val userCard2 = Color(0xFF123C46)
    val onUserCard = Color(0xFFEAF7FA)
    val accentPrimary = Color(0xFF0CC0DF)
    val accentWarm = Color(0xFFFB923C)
    val accentSecondary = Color(0xFF38BDF8)
    val accentTertiary = Color(0xFF2DD4BF)
    val accentQuaternary = Color(0xFF818CF8)
    val accentPrimarySoft = Color(0x290CC0DF)
    val accentWarmSoft = Color(0x29FB923C)
    val accentPrimaryHi = Color(0xFF2EC9E4)
    val onAccent = Color(0xFF062A31)
    val accentSecondarySoft = Color(0x2938BDF8)
    val accentTertiarySoft = Color(0x292DD4BF)
    val accentQuaternarySoft = Color(0x29818CF8)
    val engineCloud = Color(0xFF0CC0DF)
    val engineNockerl = Color(0xFF2DD4BF)
    val engineCloudSoft = Color(0x290CC0DF)
    val engineNockerlSoft = Color(0x292DD4BF)
    val statusSuccess = Color(0xFF4CAF50)
    val statusWarning = Color(0xFFFFC107)
    val statusError = Color(0xFFEF5350)
    val statusInfo = Color(0xFF0CC0DF)
    val dotStreaming = Color(0xFF0CC0DF)
    val dotAttention = Color(0xFFFFC107)
    val dotUnread = Color(0xFF38BDF8)
    val dotIdle = Color(0xFF6B6B6B)
    val dotActive = Color(0xFF34D399)
    val divider = Color(0x1FFFFFFF)
    val outlineSubtle = Color(0xFF2E2E2E)
    val shadowTint = Color(0xFF000000)
    val surfaceHighlight = Color(0x0FFFFFFF)
    val scrim = Color(0xB3000000)
    val bezel = Color(0xFF050608)
    val accentPrimaryDark = Color(0xFF0A9BB5)
    val surfaceFacetBase = Color(0xFF181B20)
}

/** Light-theme palette. Color(0xAARRGGBB). */
object NockerlLightColors {
    val coreWhite = Color(0xFFFFFFFF)
    val coreBlack = Color(0xFF000000)
    val coreCyan300 = Color(0xFF5ED4E8)
    val coreCyan400 = Color(0xFF22D3EE)
    val coreCyan500 = Color(0xFF0CC0DF)
    val coreCyan600 = Color(0xFF0A9BB5)
    val coreCyan700 = Color(0xFF0891B2)
    val coreCyan800 = Color(0xFF0E7490)
    val coreCyan900 = Color(0xFF155E75)
    val coreOrange400 = Color(0xFFFB923C)
    val coreOrange500 = Color(0xFFF97316)
    val coreOrange600 = Color(0xFFEA580C)
    val coreStatusSuccess = Color(0xFF4CAF50)
    val coreStatusSuccessDeep = Color(0xFF2E7D32)
    val coreStatusWarning = Color(0xFFFFC107)
    val coreStatusWarningDeep = Color(0xFFB7791F)
    val coreStatusError = Color(0xFFEF5350)
    val coreStatusErrorDeep = Color(0xFFD32F2F)
    val coreCategoricalCyan400 = Color(0xFF22D3EE)
    val coreCategoricalOrange400 = Color(0xFFFB923C)
    val coreCategoricalIndigo400 = Color(0xFF818CF8)
    val coreCategoricalSky400 = Color(0xFF38BDF8)
    val coreCategoricalFuchsia400 = Color(0xFFE879F9)
    val coreCategoricalViolet400 = Color(0xFFA78BFA)
    val coreCategoricalPink400 = Color(0xFFF472B6)
    val coreCategoricalEmerald400 = Color(0xFF34D399)
    val coreCategoricalTeal400 = Color(0xFF2DD4BF)
    val coreCategoricalPurple400 = Color(0xFFC084FC)
    val coreCategoricalGreen400 = Color(0xFF4ADE80)
    val coreCategoricalSky600 = Color(0xFF0284C7)
    val coreCategoricalTeal600 = Color(0xFF0D9488)
    val coreCategoricalIndigo600 = Color(0xFF4F46E5)
    val coreLogoInk = Color(0xFF555555)
    val coreLogoInkHi = Color(0xFF222222)
    val coreLogoInkLo = Color(0xFF777777)
    val coreLogoInverse = Color(0xFFE5E5E5)
    val coreLogoInverseHi = Color(0xFFFFFFFF)
    val coreLogoInverseLo = Color(0xFFCCCCCC)
    val familyShellFs = Color(0xFF22D3EE)
    val familyAgent = Color(0xFFFB923C)
    val familyScheduling = Color(0xFF818CF8)
    val familyPlanning = Color(0xFF38BDF8)
    val familyExternal = Color(0xFFE879F9)
    val modelTypeGpu = Color(0xFFA78BFA)
    val modelTypeLlm = Color(0xFFC084FC)
    val modelTypeEmbedding = Color(0xFF34D399)
    val modelTypeVision = Color(0xFF38BDF8)
    val modelTypeAudio = Color(0xFFF472B6)
    val modelTypeCreative = Color(0xFFE879F9)
    val modelTypeUtility = Color(0xFF2DD4BF)
    val modelTypeTemperature = Color(0xFFFB923C)
    val fileTypeKotlin = Color(0xFFC084FC)
    val fileTypeTypescript = Color(0xFF38BDF8)
    val fileTypeJavascript = Color(0xFFFB923C)
    val fileTypeJson = Color(0xFF2DD4BF)
    val fileTypeCss = Color(0xFF818CF8)
    val fileTypeHtml = Color(0xFFE879F9)
    val fileTypeYaml = Color(0xFF34D399)
    val fileTypeShell = Color(0xFF4ADE80)
    val fileTypePython = Color(0xFF22D3EE)
    val fileTypeRust = Color(0xFFD32F2F)
    val fileTypeImage = Color(0xFFA78BFA)
    val fileTypeFolder = Color(0xFF38BDF8)
    val fileTypeDefault = Color(0xFF9E9E9E)
    val taskStatusTodo = Color(0xFF9E9E9E)
    val taskStatusInProgress = Color(0xFF38BDF8)
    val taskStatusBlocked = Color(0xFFD32F2F)
    val taskStatusDone = Color(0xFF2E7D32)
    val taskStatusCancelled = Color(0xFF9E9E9E)
    val taskPriorityLow = Color(0xFF2DD4BF)
    val taskPriorityMedium = Color(0xFFB7791F)
    val taskPriorityHigh = Color(0xFFFB923C)
    val taskPriorityUrgent = Color(0xFFD32F2F)
    val notifSourceSystem = Color(0xFF818CF8)
    val notifSourceAgent = Color(0xFFFB923C)
    val notifSourceTask = Color(0xFF34D399)
    val notifSourceCi = Color(0xFFA78BFA)
    val notifSourceMention = Color(0xFFE879F9)
    val notifPriorityLow = Color(0xFF9E9E9E)
    val notifPriorityNormal = Color(0xFF38BDF8)
    val notifPriorityHigh = Color(0xFFD32F2F)
    val modelBadgeLarge = Color(0xFFC084FC)
    val modelBadgeMedium = Color(0xFF818CF8)
    val modelBadgeSmall = Color(0xFF34D399)
    val modelBadgeLocal = Color(0xFF22D3EE)
    val modelBadgeOther = Color(0xFF9E9E9E)
    val canvas = Color(0xFFF3F4F6)
    val canvasAlt = Color(0xFFE9EBEE)
    val chatBg = Color(0xFFC9CED5)
    val canvasEdge = Color(0xFFD7DAE0)
    val onCanvas = Color(0xFF1A1A1A)
    val onCanvasMuted = Color(0xFF5A5A5A)
    val cardSurface1 = Color(0xFFFFFFFF)
    val cardSurface2 = Color(0xFFFAFBFC)
    val cardSurface3 = Color(0xFFF0F2F5)
    val onCard = Color(0xFF1A1A1A)
    val onCardMuted = Color(0xFF5A5A5A)
    val cardHairline = Color(0x0F1A1A1A)
    val chromeSurface = Color(0xFFFFFFFF)
    val chromeActive = Color(0xFFF0F2F5)
    val onChrome = Color(0xFF1A1A1A)
    val onChromeMuted = Color(0xFF5A5A5A)
    val chromeHairline = Color(0x0F1A1A1A)
    val surfaceTranslucencySidebar = Color(0x8CFFFFFF)
    val sessionChipActive = Color(0xFF0891B2)
    val onSessionChip = Color(0xFFFFFFFF)
    val sessionChipInactive = Color(0xFF28A6BD)
    val sessionChipNew = Color(0xFF6B7280)
    val cardAlt = Color(0xFFFAFBFC)
    val cardAlt2 = Color(0xFFF0F2F5)
    val onCardAlt = Color(0xFF1A1A1A)
    val onCardAltMuted = Color(0xFF5A5A5A)
    val altHairline = Color(0x0D1A1A1A)
    val userCard = Color(0xFFCDEDF5)
    val userCard2 = Color(0xFFE6F8FC)
    val onUserCard = Color(0xFF0B2A31)
    val accentPrimary = Color(0xFF0891B2)
    val accentWarm = Color(0xFFEA580C)
    val accentSecondary = Color(0xFF0284C7)
    val accentTertiary = Color(0xFF0D9488)
    val accentQuaternary = Color(0xFF4F46E5)
    val accentPrimarySoft = Color(0x290891B2)
    val accentWarmSoft = Color(0x29EA580C)
    val accentPrimaryHi = Color(0xFF2BA0BD)
    val onAccent = Color(0xFFFFFFFF)
    val accentSecondarySoft = Color(0x290284C7)
    val accentTertiarySoft = Color(0x290D9488)
    val accentQuaternarySoft = Color(0x294F46E5)
    val engineCloud = Color(0xFF0891B2)
    val engineNockerl = Color(0xFF0D9488)
    val engineCloudSoft = Color(0x290891B2)
    val engineNockerlSoft = Color(0x290D9488)
    val statusSuccess = Color(0xFF2E7D32)
    val statusWarning = Color(0xFFB7791F)
    val statusError = Color(0xFFD32F2F)
    val statusInfo = Color(0xFF0891B2)
    val dotStreaming = Color(0xFF0891B2)
    val dotAttention = Color(0xFFB7791F)
    val dotUnread = Color(0xFF0284C7)
    val dotIdle = Color(0xFF9E9E9E)
    val dotActive = Color(0xFF2E7D32)
    val divider = Color(0x141A1A1A)
    val outlineSubtle = Color(0xFFD7DAE0)
    val shadowTint = Color(0xFF1A2733)
    val surfaceHighlight = Color(0x14FFFFFF)
    val scrim = Color(0x661A1A1A)
    val bezel = Color(0xFFD7DAE0)
    val accentPrimaryDark = Color(0xFF155E75)
    val surfaceFacetBase = Color(0xFFC9CED5)
}

/** Corner radii (dp). Theme-agnostic. */
object Radius {
    val none = 0.dp
    val track = 2.dp
    val control = 12.dp
    val panel = 12.dp
    val card = 16.dp
    val bubble = 20.dp
    val bubbleTail = 6.dp
    val pill = 9999.dp
    val chamfer = 14.dp
}

/** Elevation / drop-shadow blur levels (dp). */
object Elevation {
    val level1 = 1.dp
    val level2 = 1.5.dp
    val level3 = 3.dp
    val sheet = 5.dp
    val blur = 0.dp
}

/** Lift-shadow opacity ladder (Float 0..1): pair with Elevation blur; apply as
 *  shadowTint.copy(alpha = NockerlShadowTintAlpha.levelN). NOT a dimension. */
object NockerlShadowTintAlpha {
    val level1 = 0.28f
    val level2 = 0.3f
    val level3 = 0.33f
    val sheet = 0.35f
}

/** Cyan-stroke weight scale (dp). The weight is SEMANTIC (design-laws §2):
 *  widthFloating = hovering ON TOP of content; widthSelection = a CHOICE state
 *  (pair with NockerlBorderOpacity.selection); widthIndicator = the sliding marker bar. */
object NockerlBorder {
    val widthFloating = 1.5.dp
    val widthSelection = 1.dp
    val widthIndicator = 1.dp
}

/** Stroke opacities (Float 0..1). Apply as accentPrimary.copy(alpha = …). NOT a dimension. */
object NockerlBorderOpacity {
    val selection = 0.45f
}

/** 4px-grid spacing scale (dp). */
object Space {
    val space0 = 0.dp
    val space1 = 4.dp
    val space2 = 8.dp
    val space3 = 12.dp
    val space4 = 16.dp
    val space5 = 20.dp
    val space6 = 24.dp
    val space8 = 32.dp
    val space10 = 40.dp
    val space12 = 48.dp
    val space16 = 64.dp
    val spacePx = 1.dp
    val space05 = 2.dp
}

/** Type ramp font sizes (sp). */
object FontSize {
    val size10 = 10.sp
    val size12 = 12.sp
    val size14 = 14.sp
    val size16 = 16.sp
    val size18 = 18.sp
    val size20 = 20.sp
    val size24 = 24.sp
    val size28 = 28.sp
    val size32 = 32.sp
    val size36 = 36.sp
}

/** Page-grid rhythm (dp): gutter, min outer margin, container clamps (). */
object NockerlGrid {
    val gutter = 20.dp
    val margin = 16.dp
    val containerMd = 768.dp
    val containerLg = 1024.dp
    val containerXl = 1280.dp
}

/** Density tiers (dp): row height + vertical padding per tier (). */
object NockerlDensity {
    val rowHeightCompact = 32.dp
    val rowHeightComfortable = 48.dp
    val padYCompact = 4.dp
    val padYComfortable = 12.dp
}

/** Semantic sizes (dp): touch/divider/panel minimums, container + chat-width caps (). */
object NockerlSize {
    val minTouch = 44.dp
    val dividerSignature = 1.5.dp
    val chartMin = 92.dp
    val panelMin = 132.dp
    val selectMaxHeight = 400.dp
    val containerXs = 216.dp
    val containerSm = 220.dp
    val containerMd = 264.dp
    val containerLg = 360.dp
    val chatBubbleMax = 460.dp
    val chatToolCardMax = 560.dp
    val chatBannerMax = 540.dp
    val chatColumnMax = 1040.dp
}

data class NockerlTextStyle(
    val fontFamily: String,
    val fontWeight: Int,
    val fontSize: TextUnit,
    val lineHeight: TextUnit,
)

/** Material 3 type ramp (best-effort: family/weight/size/line-height). */
object NockerlType {
    val displayLarge = NockerlTextStyle("Outfit", 100, 36.sp, 44.sp)
    val displayMedium = NockerlTextStyle("Outfit", 100, 32.sp, 40.sp)
    val displaySmall = NockerlTextStyle("Outfit", 100, 28.sp, 36.sp)
    val headlineLarge = NockerlTextStyle("Outfit", 200, 28.sp, 36.sp)
    val headlineMedium = NockerlTextStyle("Outfit", 200, 24.sp, 32.sp)
    val headlineSmall = NockerlTextStyle("Outfit", 500, 20.sp, 28.sp)
    val titleLarge = NockerlTextStyle("Outfit", 500, 18.sp, 26.sp)
    val titleMedium = NockerlTextStyle("Outfit", 500, 16.sp, 24.sp)
    val titleSmall = NockerlTextStyle("Outfit", 500, 14.sp, 20.sp)
    val bodyLarge = NockerlTextStyle("Outfit", 300, 16.sp, 24.sp)
    val bodyMedium = NockerlTextStyle("Outfit", 300, 14.sp, 20.sp)
    val bodySmall = NockerlTextStyle("Outfit", 300, 12.sp, 16.sp)
    val labelLarge = NockerlTextStyle("Outfit", 300, 14.sp, 20.sp)
    val labelMedium = NockerlTextStyle("Outfit", 300, 12.sp, 16.sp)
    val labelSmall = NockerlTextStyle("Outfit", 300, 10.sp, 14.sp)
    val eyebrow = NockerlTextStyle("Outfit", 500, 12.sp, 16.sp)
}

/** Motion durations (integer milliseconds). RATIFIED r3. */
object NockerlMotionDuration {
    val instantMs = 0
    val fastMs = 120
    val baseMs = 200
    val slowMs = 320
    val sheetMs = 400
    val pulseMs = 800
}

/** Motion easing curves. `standard` is THE default transition ease. */
object NockerlMotionEasing {
    val standard = CubicBezierEasing(0.2f, 0f, 0f, 1f)
    val emphasized = CubicBezierEasing(0.05f, 0.7f, 0.1f, 1f)
    val exit = CubicBezierEasing(0.3f, 0f, 0.8f, 0.15f)
}
