// Assemble the @dizyx/nockerl-tokens package from the generated web build. Run AFTER the
// Style Dictionary build (it is chained into `bun run build`). Ships FOUR files under dist/:
//
//   - tokens.css:    the CSS custom properties (the canonical web consumable, :root + dark).
//   - tokens.json:   { "<token-name>": { light, dark } }, the typed data map for tooling / the MCP.
//   - index.js:      the SELF-CONTAINED typed token map + a cssVar() helper (inlines the data,
//                    so there is no runtime JSON import), the app-code entry.
//   - index.d.ts:    the TS surface: a TokenName union, the typed `tokens` map, cssVar().
//
// The JSON + typed map are parsed straight from the generated tokens.css (the single source of
// truth for the web output), so they can never drift from the CSS.
import { mkdir, writeFile, copyFile } from 'node:fs/promises';

const SRC = 'build/web/tokens.css';
const DEST_DIR = 'packages/tokens/dist';

if (!(await Bun.file(SRC).exists())) {
  throw new Error(`Missing ${SRC}: run \`bun run build\` first.`);
}
const css = await Bun.file(SRC).text();

// Pull a { --name: value; } block into a name → value map (name stripped of the -- prefix).
function block(re: RegExp): Record<string, string> {
  const m = css.match(re);
  const out: Record<string, string> = {};
  if (!m) return out;
  for (const line of m[1]!.split('\n')) {
    const p = line.match(/^\s*--([a-z0-9-]+):\s*(.+?);\s*$/i);
    if (p) out[p[1]!] = p[2]!.trim();
  }
  return out;
}
const light = block(/:root\s*\{([\s\S]*?)\n\}/);
const dark = block(/:root\[data-theme=['"]dark['"]\]\s*\{([\s\S]*?)\n\}/);

// Every token carries BOTH themes; a token defined in only one falls back to that value.
const names = Array.from(new Set([...Object.keys(light), ...Object.keys(dark)])).sort();
const tokens: Record<string, { light: string; dark: string }> = {};
for (const n of names) tokens[n] = { light: light[n] ?? dark[n]!, dark: dark[n] ?? light[n]! };

await mkdir(DEST_DIR, { recursive: true });
await copyFile(SRC, `${DEST_DIR}/tokens.css`);
await writeFile(`${DEST_DIR}/tokens.json`, JSON.stringify(tokens, null, 2) + '\n');

// index.js: inlines the map (no runtime JSON import) + the cssVar helper (string concat, so the
// generated file carries no backticks). ESM (the package is "type": "module").
const indexJs = `// GENERATED by scripts/pack-tokens.ts: do not edit by hand.
export const tokens = ${JSON.stringify(tokens, null, 2)};
export const tokenNames = Object.keys(tokens);
/** The CSS var() reference for a token: the type-safe way to consume a token in JS. */
export function cssVar(name) { return 'var(--' + name + ')'; }
`;
await writeFile(`${DEST_DIR}/index.js`, indexJs);

// index.d.ts: the TokenName union + the typed map + cssVar().
const union = names.map((n) => `  | '${n}'`).join('\n');
const indexDts = `// GENERATED by scripts/pack-tokens.ts: do not edit by hand.
export type TokenName =
${union};
/** A token's value in each theme. */
export interface TokenValue { light: string; dark: string; }
/** The full token map: every name to its light / dark value. */
export declare const tokens: Record<TokenName, TokenValue>;
/** All token names. */
export declare const tokenNames: TokenName[];
/** The CSS var() reference for a token, e.g. cssVar('color-accent-primary') === 'var(--color-accent-primary)'. */
export declare function cssVar(name: TokenName): string;
`;
await writeFile(`${DEST_DIR}/index.d.ts`, indexDts);

console.log(`Packed @dizyx/nockerl-tokens → ${DEST_DIR} (tokens.css + tokens.json + index.js + index.d.ts, ${names.length} tokens).`);
