// Nockerl design tokens: GENERATED by Style Dictionary. Do not edit by hand.
// Source of truth: tokens/*.json  •  Build: bun run build

import CoreGraphics
import Foundation
import SwiftUI

/// Dark-theme palette.
public enum NockerlDarkColors {
    public static let coreWhite = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let coreBlack = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 1)
    public static let coreCyan300 = Color(red: 0.369, green: 0.831, blue: 0.910, opacity: 1)
    public static let coreCyan400 = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let coreCyan500 = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 1)
    public static let coreCyan600 = Color(red: 0.039, green: 0.608, blue: 0.710, opacity: 1)
    public static let coreCyan700 = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 1)
    public static let coreCyan800 = Color(red: 0.055, green: 0.455, blue: 0.565, opacity: 1)
    public static let coreCyan900 = Color(red: 0.082, green: 0.369, blue: 0.459, opacity: 1)
    public static let coreOrange400 = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let coreOrange500 = Color(red: 0.976, green: 0.451, blue: 0.086, opacity: 1)
    public static let coreOrange600 = Color(red: 0.918, green: 0.345, blue: 0.047, opacity: 1)
    public static let coreStatusSuccess = Color(red: 0.298, green: 0.686, blue: 0.314, opacity: 1)
    public static let coreStatusSuccessDeep = Color(red: 0.180, green: 0.490, blue: 0.196, opacity: 1)
    public static let coreStatusWarning = Color(red: 1.000, green: 0.757, blue: 0.027, opacity: 1)
    public static let coreStatusWarningDeep = Color(red: 0.718, green: 0.475, blue: 0.122, opacity: 1)
    public static let coreStatusError = Color(red: 0.937, green: 0.325, blue: 0.314, opacity: 1)
    public static let coreStatusErrorDeep = Color(red: 0.827, green: 0.184, blue: 0.184, opacity: 1)
    public static let coreCategoricalCyan400 = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let coreCategoricalOrange400 = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let coreCategoricalIndigo400 = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let coreCategoricalSky400 = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let coreCategoricalFuchsia400 = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let coreCategoricalViolet400 = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let coreCategoricalPink400 = Color(red: 0.957, green: 0.447, blue: 0.714, opacity: 1)
    public static let coreCategoricalEmerald400 = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let coreCategoricalTeal400 = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let coreCategoricalPurple400 = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let coreCategoricalGreen400 = Color(red: 0.290, green: 0.871, blue: 0.502, opacity: 1)
    public static let coreCategoricalSky600 = Color(red: 0.008, green: 0.518, blue: 0.780, opacity: 1)
    public static let coreCategoricalTeal600 = Color(red: 0.051, green: 0.580, blue: 0.533, opacity: 1)
    public static let coreCategoricalIndigo600 = Color(red: 0.310, green: 0.275, blue: 0.898, opacity: 1)
    public static let coreLogoInk = Color(red: 0.333, green: 0.333, blue: 0.333, opacity: 1)
    public static let coreLogoInkHi = Color(red: 0.133, green: 0.133, blue: 0.133, opacity: 1)
    public static let coreLogoInkLo = Color(red: 0.467, green: 0.467, blue: 0.467, opacity: 1)
    public static let coreLogoInverse = Color(red: 0.898, green: 0.898, blue: 0.898, opacity: 1)
    public static let coreLogoInverseHi = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let coreLogoInverseLo = Color(red: 0.800, green: 0.800, blue: 0.800, opacity: 1)
    public static let familyShellFs = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let familyAgent = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let familyScheduling = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let familyPlanning = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let familyExternal = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let modelTypeGpu = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let modelTypeLlm = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let modelTypeEmbedding = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let modelTypeVision = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let modelTypeAudio = Color(red: 0.957, green: 0.447, blue: 0.714, opacity: 1)
    public static let modelTypeCreative = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let modelTypeUtility = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let modelTypeTemperature = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let fileTypeKotlin = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let fileTypeTypescript = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let fileTypeJavascript = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let fileTypeJson = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let fileTypeCss = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let fileTypeHtml = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let fileTypeYaml = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let fileTypeShell = Color(red: 0.290, green: 0.871, blue: 0.502, opacity: 1)
    public static let fileTypePython = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let fileTypeRust = Color(red: 0.937, green: 0.325, blue: 0.314, opacity: 1)
    public static let fileTypeImage = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let fileTypeFolder = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let fileTypeDefault = Color(red: 0.420, green: 0.420, blue: 0.420, opacity: 1)
    public static let taskStatusTodo = Color(red: 0.420, green: 0.420, blue: 0.420, opacity: 1)
    public static let taskStatusInProgress = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let taskStatusBlocked = Color(red: 0.937, green: 0.325, blue: 0.314, opacity: 1)
    public static let taskStatusDone = Color(red: 0.298, green: 0.686, blue: 0.314, opacity: 1)
    public static let taskStatusCancelled = Color(red: 0.420, green: 0.420, blue: 0.420, opacity: 1)
    public static let taskPriorityLow = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let taskPriorityMedium = Color(red: 1.000, green: 0.757, blue: 0.027, opacity: 1)
    public static let taskPriorityHigh = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let taskPriorityUrgent = Color(red: 0.937, green: 0.325, blue: 0.314, opacity: 1)
    public static let notifSourceSystem = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let notifSourceAgent = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let notifSourceTask = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let notifSourceCi = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let notifSourceMention = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let notifPriorityLow = Color(red: 0.420, green: 0.420, blue: 0.420, opacity: 1)
    public static let notifPriorityNormal = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let notifPriorityHigh = Color(red: 0.937, green: 0.325, blue: 0.314, opacity: 1)
    public static let modelBadgeLarge = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let modelBadgeMedium = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let modelBadgeSmall = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let modelBadgeLocal = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let modelBadgeOther = Color(red: 0.420, green: 0.420, blue: 0.420, opacity: 1)
    public static let canvas = Color(red: 0.039, green: 0.043, blue: 0.051, opacity: 1)
    public static let canvasAlt = Color(red: 0.067, green: 0.075, blue: 0.090, opacity: 1)
    public static let chatBg = Color(red: 0.094, green: 0.106, blue: 0.125, opacity: 1)
    public static let canvasEdge = Color(red: 0.165, green: 0.176, blue: 0.200, opacity: 1)
    public static let onCanvas = Color(red: 0.910, green: 0.910, blue: 0.910, opacity: 1)
    public static let onCanvasMuted = Color(red: 0.627, green: 0.627, blue: 0.627, opacity: 1)
    public static let cardSurface1 = Color(red: 0.173, green: 0.192, blue: 0.227, opacity: 1)
    public static let cardSurface2 = Color(red: 0.200, green: 0.224, blue: 0.259, opacity: 1)
    public static let cardSurface3 = Color(red: 0.227, green: 0.255, blue: 0.290, opacity: 1)
    public static let onCard = Color(red: 0.910, green: 0.910, blue: 0.910, opacity: 1)
    public static let onCardMuted = Color(red: 0.627, green: 0.627, blue: 0.627, opacity: 1)
    public static let cardHairline = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.0784313725490196)
    public static let chromeSurface = Color(red: 0.082, green: 0.090, blue: 0.102, opacity: 1)
    public static let chromeActive = Color(red: 0.114, green: 0.125, blue: 0.141, opacity: 1)
    public static let onChrome = Color(red: 0.910, green: 0.910, blue: 0.910, opacity: 1)
    public static let onChromeMuted = Color(red: 0.627, green: 0.627, blue: 0.627, opacity: 1)
    public static let chromeHairline = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.0784313725490196)
    public static let surfaceTranslucencySidebar = Color(red: 0.082, green: 0.090, blue: 0.102, opacity: 0.5490196078431373)
    public static let sessionChipActive = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 1)
    public static let onSessionChip = Color(red: 0.039, green: 0.043, blue: 0.051, opacity: 1)
    public static let sessionChipInactive = Color(red: 0.039, green: 0.608, blue: 0.710, opacity: 1)
    public static let sessionChipNew = Color(red: 0.294, green: 0.333, blue: 0.388, opacity: 1)
    public static let cardAlt = Color(red: 0.173, green: 0.192, blue: 0.227, opacity: 1)
    public static let cardAlt2 = Color(red: 0.212, green: 0.235, blue: 0.271, opacity: 1)
    public static let onCardAlt = Color(red: 0.910, green: 0.910, blue: 0.910, opacity: 1)
    public static let onCardAltMuted = Color(red: 0.627, green: 0.627, blue: 0.627, opacity: 1)
    public static let altHairline = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.06274509803921569)
    public static let userCard = Color(red: 0.047, green: 0.165, blue: 0.192, opacity: 1)
    public static let userCard2 = Color(red: 0.071, green: 0.235, blue: 0.275, opacity: 1)
    public static let onUserCard = Color(red: 0.918, green: 0.969, blue: 0.980, opacity: 1)
    public static let accentPrimary = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 1)
    public static let accentWarm = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let accentSecondary = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let accentTertiary = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let accentQuaternary = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let accentPrimarySoft = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 0.1607843137254902)
    public static let accentWarmSoft = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 0.1607843137254902)
    public static let accentPrimaryHi = Color(red: 0.180, green: 0.788, blue: 0.894, opacity: 1)
    public static let onAccent = Color(red: 0.024, green: 0.165, blue: 0.192, opacity: 1)
    public static let accentSecondarySoft = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 0.1607843137254902)
    public static let accentTertiarySoft = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 0.1607843137254902)
    public static let accentQuaternarySoft = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 0.1607843137254902)
    public static let engineCloud = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 1)
    public static let engineNockerl = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let engineCloudSoft = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 0.1607843137254902)
    public static let engineNockerlSoft = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 0.1607843137254902)
    public static let statusSuccess = Color(red: 0.298, green: 0.686, blue: 0.314, opacity: 1)
    public static let statusWarning = Color(red: 1.000, green: 0.757, blue: 0.027, opacity: 1)
    public static let statusError = Color(red: 0.937, green: 0.325, blue: 0.314, opacity: 1)
    public static let statusInfo = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 1)
    public static let dotStreaming = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 1)
    public static let dotAttention = Color(red: 1.000, green: 0.757, blue: 0.027, opacity: 1)
    public static let dotUnread = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let dotIdle = Color(red: 0.420, green: 0.420, blue: 0.420, opacity: 1)
    public static let dotActive = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let divider = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.12156862745098039)
    public static let outlineSubtle = Color(red: 0.180, green: 0.180, blue: 0.180, opacity: 1)
    public static let shadowTint = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 1)
    public static let surfaceHighlight = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.058823529411764705)
    public static let scrim = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.7019607843137254)
    public static let bezel = Color(red: 0.020, green: 0.024, blue: 0.031, opacity: 1)
    public static let accentPrimaryDark = Color(red: 0.039, green: 0.608, blue: 0.710, opacity: 1)
    public static let surfaceFacetBase = Color(red: 0.094, green: 0.106, blue: 0.125, opacity: 1)
}

/// Light-theme palette.
public enum NockerlLightColors {
    public static let coreWhite = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let coreBlack = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 1)
    public static let coreCyan300 = Color(red: 0.369, green: 0.831, blue: 0.910, opacity: 1)
    public static let coreCyan400 = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let coreCyan500 = Color(red: 0.047, green: 0.753, blue: 0.875, opacity: 1)
    public static let coreCyan600 = Color(red: 0.039, green: 0.608, blue: 0.710, opacity: 1)
    public static let coreCyan700 = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 1)
    public static let coreCyan800 = Color(red: 0.055, green: 0.455, blue: 0.565, opacity: 1)
    public static let coreCyan900 = Color(red: 0.082, green: 0.369, blue: 0.459, opacity: 1)
    public static let coreOrange400 = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let coreOrange500 = Color(red: 0.976, green: 0.451, blue: 0.086, opacity: 1)
    public static let coreOrange600 = Color(red: 0.918, green: 0.345, blue: 0.047, opacity: 1)
    public static let coreStatusSuccess = Color(red: 0.298, green: 0.686, blue: 0.314, opacity: 1)
    public static let coreStatusSuccessDeep = Color(red: 0.180, green: 0.490, blue: 0.196, opacity: 1)
    public static let coreStatusWarning = Color(red: 1.000, green: 0.757, blue: 0.027, opacity: 1)
    public static let coreStatusWarningDeep = Color(red: 0.718, green: 0.475, blue: 0.122, opacity: 1)
    public static let coreStatusError = Color(red: 0.937, green: 0.325, blue: 0.314, opacity: 1)
    public static let coreStatusErrorDeep = Color(red: 0.827, green: 0.184, blue: 0.184, opacity: 1)
    public static let coreCategoricalCyan400 = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let coreCategoricalOrange400 = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let coreCategoricalIndigo400 = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let coreCategoricalSky400 = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let coreCategoricalFuchsia400 = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let coreCategoricalViolet400 = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let coreCategoricalPink400 = Color(red: 0.957, green: 0.447, blue: 0.714, opacity: 1)
    public static let coreCategoricalEmerald400 = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let coreCategoricalTeal400 = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let coreCategoricalPurple400 = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let coreCategoricalGreen400 = Color(red: 0.290, green: 0.871, blue: 0.502, opacity: 1)
    public static let coreCategoricalSky600 = Color(red: 0.008, green: 0.518, blue: 0.780, opacity: 1)
    public static let coreCategoricalTeal600 = Color(red: 0.051, green: 0.580, blue: 0.533, opacity: 1)
    public static let coreCategoricalIndigo600 = Color(red: 0.310, green: 0.275, blue: 0.898, opacity: 1)
    public static let coreLogoInk = Color(red: 0.333, green: 0.333, blue: 0.333, opacity: 1)
    public static let coreLogoInkHi = Color(red: 0.133, green: 0.133, blue: 0.133, opacity: 1)
    public static let coreLogoInkLo = Color(red: 0.467, green: 0.467, blue: 0.467, opacity: 1)
    public static let coreLogoInverse = Color(red: 0.898, green: 0.898, blue: 0.898, opacity: 1)
    public static let coreLogoInverseHi = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let coreLogoInverseLo = Color(red: 0.800, green: 0.800, blue: 0.800, opacity: 1)
    public static let familyShellFs = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let familyAgent = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let familyScheduling = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let familyPlanning = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let familyExternal = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let modelTypeGpu = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let modelTypeLlm = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let modelTypeEmbedding = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let modelTypeVision = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let modelTypeAudio = Color(red: 0.957, green: 0.447, blue: 0.714, opacity: 1)
    public static let modelTypeCreative = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let modelTypeUtility = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let modelTypeTemperature = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let fileTypeKotlin = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let fileTypeTypescript = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let fileTypeJavascript = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let fileTypeJson = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let fileTypeCss = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let fileTypeHtml = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let fileTypeYaml = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let fileTypeShell = Color(red: 0.290, green: 0.871, blue: 0.502, opacity: 1)
    public static let fileTypePython = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let fileTypeRust = Color(red: 0.827, green: 0.184, blue: 0.184, opacity: 1)
    public static let fileTypeImage = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let fileTypeFolder = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let fileTypeDefault = Color(red: 0.620, green: 0.620, blue: 0.620, opacity: 1)
    public static let taskStatusTodo = Color(red: 0.620, green: 0.620, blue: 0.620, opacity: 1)
    public static let taskStatusInProgress = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let taskStatusBlocked = Color(red: 0.827, green: 0.184, blue: 0.184, opacity: 1)
    public static let taskStatusDone = Color(red: 0.180, green: 0.490, blue: 0.196, opacity: 1)
    public static let taskStatusCancelled = Color(red: 0.620, green: 0.620, blue: 0.620, opacity: 1)
    public static let taskPriorityLow = Color(red: 0.176, green: 0.831, blue: 0.749, opacity: 1)
    public static let taskPriorityMedium = Color(red: 0.718, green: 0.475, blue: 0.122, opacity: 1)
    public static let taskPriorityHigh = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let taskPriorityUrgent = Color(red: 0.827, green: 0.184, blue: 0.184, opacity: 1)
    public static let notifSourceSystem = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let notifSourceAgent = Color(red: 0.984, green: 0.573, blue: 0.235, opacity: 1)
    public static let notifSourceTask = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let notifSourceCi = Color(red: 0.655, green: 0.545, blue: 0.980, opacity: 1)
    public static let notifSourceMention = Color(red: 0.910, green: 0.475, blue: 0.976, opacity: 1)
    public static let notifPriorityLow = Color(red: 0.620, green: 0.620, blue: 0.620, opacity: 1)
    public static let notifPriorityNormal = Color(red: 0.220, green: 0.741, blue: 0.973, opacity: 1)
    public static let notifPriorityHigh = Color(red: 0.827, green: 0.184, blue: 0.184, opacity: 1)
    public static let modelBadgeLarge = Color(red: 0.753, green: 0.518, blue: 0.988, opacity: 1)
    public static let modelBadgeMedium = Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 1)
    public static let modelBadgeSmall = Color(red: 0.204, green: 0.827, blue: 0.600, opacity: 1)
    public static let modelBadgeLocal = Color(red: 0.133, green: 0.827, blue: 0.933, opacity: 1)
    public static let modelBadgeOther = Color(red: 0.620, green: 0.620, blue: 0.620, opacity: 1)
    public static let canvas = Color(red: 0.953, green: 0.957, blue: 0.965, opacity: 1)
    public static let canvasAlt = Color(red: 0.914, green: 0.922, blue: 0.933, opacity: 1)
    public static let chatBg = Color(red: 0.788, green: 0.808, blue: 0.835, opacity: 1)
    public static let canvasEdge = Color(red: 0.843, green: 0.855, blue: 0.878, opacity: 1)
    public static let onCanvas = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 1)
    public static let onCanvasMuted = Color(red: 0.353, green: 0.353, blue: 0.353, opacity: 1)
    public static let cardSurface1 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let cardSurface2 = Color(red: 0.980, green: 0.984, blue: 0.988, opacity: 1)
    public static let cardSurface3 = Color(red: 0.941, green: 0.949, blue: 0.961, opacity: 1)
    public static let onCard = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 1)
    public static let onCardMuted = Color(red: 0.353, green: 0.353, blue: 0.353, opacity: 1)
    public static let cardHairline = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 0.058823529411764705)
    public static let chromeSurface = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let chromeActive = Color(red: 0.941, green: 0.949, blue: 0.961, opacity: 1)
    public static let onChrome = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 1)
    public static let onChromeMuted = Color(red: 0.353, green: 0.353, blue: 0.353, opacity: 1)
    public static let chromeHairline = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 0.058823529411764705)
    public static let surfaceTranslucencySidebar = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.5490196078431373)
    public static let sessionChipActive = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 1)
    public static let onSessionChip = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let sessionChipInactive = Color(red: 0.157, green: 0.651, blue: 0.741, opacity: 1)
    public static let sessionChipNew = Color(red: 0.420, green: 0.447, blue: 0.502, opacity: 1)
    public static let cardAlt = Color(red: 0.980, green: 0.984, blue: 0.988, opacity: 1)
    public static let cardAlt2 = Color(red: 0.941, green: 0.949, blue: 0.961, opacity: 1)
    public static let onCardAlt = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 1)
    public static let onCardAltMuted = Color(red: 0.353, green: 0.353, blue: 0.353, opacity: 1)
    public static let altHairline = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 0.050980392156862744)
    public static let userCard = Color(red: 0.804, green: 0.929, blue: 0.961, opacity: 1)
    public static let userCard2 = Color(red: 0.902, green: 0.973, blue: 0.988, opacity: 1)
    public static let onUserCard = Color(red: 0.043, green: 0.165, blue: 0.192, opacity: 1)
    public static let accentPrimary = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 1)
    public static let accentWarm = Color(red: 0.918, green: 0.345, blue: 0.047, opacity: 1)
    public static let accentSecondary = Color(red: 0.008, green: 0.518, blue: 0.780, opacity: 1)
    public static let accentTertiary = Color(red: 0.051, green: 0.580, blue: 0.533, opacity: 1)
    public static let accentQuaternary = Color(red: 0.310, green: 0.275, blue: 0.898, opacity: 1)
    public static let accentPrimarySoft = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 0.1607843137254902)
    public static let accentWarmSoft = Color(red: 0.918, green: 0.345, blue: 0.047, opacity: 0.1607843137254902)
    public static let accentPrimaryHi = Color(red: 0.169, green: 0.627, blue: 0.741, opacity: 1)
    public static let onAccent = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let accentSecondarySoft = Color(red: 0.008, green: 0.518, blue: 0.780, opacity: 0.1607843137254902)
    public static let accentTertiarySoft = Color(red: 0.051, green: 0.580, blue: 0.533, opacity: 0.1607843137254902)
    public static let accentQuaternarySoft = Color(red: 0.310, green: 0.275, blue: 0.898, opacity: 0.1607843137254902)
    public static let engineCloud = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 1)
    public static let engineNockerl = Color(red: 0.051, green: 0.580, blue: 0.533, opacity: 1)
    public static let engineCloudSoft = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 0.1607843137254902)
    public static let engineNockerlSoft = Color(red: 0.051, green: 0.580, blue: 0.533, opacity: 0.1607843137254902)
    public static let statusSuccess = Color(red: 0.180, green: 0.490, blue: 0.196, opacity: 1)
    public static let statusWarning = Color(red: 0.718, green: 0.475, blue: 0.122, opacity: 1)
    public static let statusError = Color(red: 0.827, green: 0.184, blue: 0.184, opacity: 1)
    public static let statusInfo = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 1)
    public static let dotStreaming = Color(red: 0.031, green: 0.569, blue: 0.698, opacity: 1)
    public static let dotAttention = Color(red: 0.718, green: 0.475, blue: 0.122, opacity: 1)
    public static let dotUnread = Color(red: 0.008, green: 0.518, blue: 0.780, opacity: 1)
    public static let dotIdle = Color(red: 0.620, green: 0.620, blue: 0.620, opacity: 1)
    public static let dotActive = Color(red: 0.180, green: 0.490, blue: 0.196, opacity: 1)
    public static let divider = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 0.0784313725490196)
    public static let outlineSubtle = Color(red: 0.843, green: 0.855, blue: 0.878, opacity: 1)
    public static let shadowTint = Color(red: 0.102, green: 0.153, blue: 0.200, opacity: 1)
    public static let surfaceHighlight = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.0784313725490196)
    public static let scrim = Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 0.4)
    public static let bezel = Color(red: 0.843, green: 0.855, blue: 0.878, opacity: 1)
    public static let accentPrimaryDark = Color(red: 0.082, green: 0.369, blue: 0.459, opacity: 1)
    public static let surfaceFacetBase = Color(red: 0.788, green: 0.808, blue: 0.835, opacity: 1)
}

/// Corner radii (pt). Theme-agnostic.
public enum NockerlRadius {
    public static let none: CGFloat = 0
    public static let track: CGFloat = 2
    public static let control: CGFloat = 12
    public static let panel: CGFloat = 12
    public static let card: CGFloat = 16
    public static let bubble: CGFloat = 20
    public static let bubbleTail: CGFloat = 6
    public static let pill: CGFloat = 9999
}

/// Elevation / drop-shadow blur levels (pt).
public enum NockerlElevation {
    public static let level1: CGFloat = 1
    public static let level2: CGFloat = 1.5
    public static let level3: CGFloat = 3
    public static let sheet: CGFloat = 5
    public static let blur: CGFloat = 0
}

/// Lift-shadow opacity ladder (Double 0..1): pair with NockerlElevation blur;
/// apply as shadowTint.opacity(NockerlShadowTintAlpha.levelN). NOT a dimension.
public enum NockerlShadowTintAlpha {
    public static let level1: Double = 0.28
    public static let level2: Double = 0.3
    public static let level3: Double = 0.33
    public static let sheet: Double = 0.35
}

/// Cyan-stroke weight scale (pt). The weight is SEMANTIC (design-laws §2):
/// widthFloating = hovering ON TOP of content; widthSelection = a CHOICE state
/// (pair with NockerlBorderOpacity.selection); widthIndicator = the sliding marker bar.
public enum NockerlBorder {
    public static let widthFloating: CGFloat = 1.5
    public static let widthSelection: CGFloat = 1
    public static let widthIndicator: CGFloat = 1
}

/// Stroke opacities (Double 0..1). Apply as accentPrimary.opacity(…). NOT dimensions.
public enum NockerlBorderOpacity {
    public static let selection: Double = 0.45
}

/// 4pt-grid spacing scale (pt).
public enum NockerlSpace {
    public static let space0: CGFloat = 0
    public static let space1: CGFloat = 4
    public static let space2: CGFloat = 8
    public static let space3: CGFloat = 12
    public static let space4: CGFloat = 16
    public static let space5: CGFloat = 20
    public static let space6: CGFloat = 24
    public static let space8: CGFloat = 32
    public static let space10: CGFloat = 40
    public static let space12: CGFloat = 48
    public static let space16: CGFloat = 64
    public static let spacePx: CGFloat = 1
    public static let space05: CGFloat = 2
}

/// Type ramp font sizes (pt).
public enum NockerlFontSize {
    public static let size10: CGFloat = 10
    public static let size12: CGFloat = 12
    public static let size14: CGFloat = 14
    public static let size16: CGFloat = 16
    public static let size18: CGFloat = 18
    public static let size20: CGFloat = 20
    public static let size24: CGFloat = 24
    public static let size28: CGFloat = 28
    public static let size32: CGFloat = 32
    public static let size36: CGFloat = 36
}

/// Page-grid rhythm (pt): gutter, min outer margin, container clamps.
public enum NockerlGrid {
    public static let gutter: CGFloat = 20
    public static let margin: CGFloat = 16
    public static let containerMd: CGFloat = 768
    public static let containerLg: CGFloat = 1024
    public static let containerXl: CGFloat = 1280
}

/// Density tiers (pt): row height + vertical padding per tier.
public enum NockerlDensity {
    public static let rowHeightCompact: CGFloat = 32
    public static let rowHeightComfortable: CGFloat = 48
    public static let padYCompact: CGFloat = 4
    public static let padYComfortable: CGFloat = 12
}

/// Semantic sizes (pt): touch/divider/panel minimums, container + chat-width caps.
public enum NockerlSize {
    public static let minTouch: CGFloat = 44
    public static let dividerSignature: CGFloat = 1.5
    public static let chartMin: CGFloat = 92
    public static let panelMin: CGFloat = 132
    public static let selectMaxHeight: CGFloat = 400
    public static let containerXs: CGFloat = 216
    public static let containerSm: CGFloat = 220
    public static let containerMd: CGFloat = 264
    public static let containerLg: CGFloat = 360
    public static let chatBubbleMax: CGFloat = 460
    public static let chatToolCardMax: CGFloat = 560
    public static let chatBannerMax: CGFloat = 540
    public static let chatColumnMax: CGFloat = 1040
}

public struct NockerlTextStyle {
    public let fontFamily: String
    public let fontWeight: Int
    public let fontSize: CGFloat
    public let lineHeight: CGFloat
}

/// Type ramp (best-effort: family/weight/size/line-height).
public enum NockerlType {
    public static let displayLarge = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 100, fontSize: 36, lineHeight: 44)
    public static let displayMedium = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 100, fontSize: 32, lineHeight: 40)
    public static let displaySmall = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 100, fontSize: 28, lineHeight: 36)
    public static let headlineLarge = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 200, fontSize: 28, lineHeight: 36)
    public static let headlineMedium = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 200, fontSize: 24, lineHeight: 32)
    public static let headlineSmall = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 500, fontSize: 20, lineHeight: 28)
    public static let titleLarge = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 500, fontSize: 18, lineHeight: 26)
    public static let titleMedium = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 500, fontSize: 16, lineHeight: 24)
    public static let titleSmall = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 500, fontSize: 14, lineHeight: 20)
    public static let bodyLarge = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 300, fontSize: 16, lineHeight: 24)
    public static let bodyMedium = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 300, fontSize: 14, lineHeight: 20)
    public static let bodySmall = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 300, fontSize: 12, lineHeight: 16)
    public static let labelLarge = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 300, fontSize: 14, lineHeight: 20)
    public static let labelMedium = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 300, fontSize: 12, lineHeight: 16)
    public static let labelSmall = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 300, fontSize: 10, lineHeight: 14)
    public static let eyebrow = NockerlTextStyle(fontFamily: "Outfit", fontWeight: 500, fontSize: 12, lineHeight: 16)
}

/// Motion durations (seconds). RATIFIED r3.
public enum NockerlMotionDuration {
    public static let instant: TimeInterval = 0
    public static let fast: TimeInterval = 0.12
    public static let base: TimeInterval = 0.2
    public static let slow: TimeInterval = 0.32
    public static let sheet: TimeInterval = 0.4
    public static let pulse: TimeInterval = 0.8
}

/// A cubic-bezier easing (control points). Feed `Animation.timingCurve`.
public struct NockerlBezier {
    public let x1: Double
    public let y1: Double
    public let x2: Double
    public let y2: Double
}

/// Motion easing curves. `standard` is THE default transition ease.
public enum NockerlMotionEasing {
    public static let standard = NockerlBezier(x1: 0.2, y1: 0, x2: 0, y2: 1)
    public static let emphasized = NockerlBezier(x1: 0.05, y1: 0.7, x2: 0.1, y2: 1)
    public static let exit = NockerlBezier(x1: 0.3, y1: 0, x2: 0.8, y2: 0.15)
}
